### ISSUE TITLE
Migration to Codecov's github application

### ISSUE THREAD

**Issue by youpong** [TanmayPatil105/procfetch#110]

**Comment by TanmayPatil105** [comment]
How to migrate?

**Comment by youpong** [comment]
For example in pull request #118, there is a PR comment to install the GitHub App Integration.
Here is a quote from [the link](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/) included in that comment:
> If you are an organization administrator who sees a notification from Codecov either in the app or in a PR comment to install the GitHub App Integration,

**Comment by TanmayPatil105** [comment]
Closing!
