### ISSUE TITLE
brew not found

### ISSUE THREAD

**Issue by akshaykhoje** [TanmayPatil105/procfetch#128]
On my Debian11 Bullseye, I have not installed brew yet.

Using the procfetch application, it shows ```brew``` not found just above the **Packages**.

![image](https://user-images.githubusercontent.com/98017423/221392006-1721d1bb-d5b3-4023-951c-34d24501d833.png)

**Comment by TanmayPatil105** [comment]
It is probably because you have brew installed ie. `Path::of("/home/linuxbrew/.linuxbrew/bin/brew"s).isExecutable()` returns true. But is is not in the `PATH`.

**Comment by akshaykhoje** [comment]
I mentioned that I have ```NOT``` installed brew yet. 

1. So the program must check for the availability of brew in path and if NOT found, we don't enlist brew package count at all.. 
2. keep brew as a dependency.

**Comment by TanmayPatil105** [comment]
Well, `Path::of("/home/linuxbrew/.linuxbrew/bin/brew"s).isExecutable()` is returning true. So, `/home/linuxbrew/.linuxbrew/bin/brew` must have been existing. Can you check?

**Comment by akshaykhoje** [comment]
Alright. Done! Works now :)
