### ISSUE TITLE
Remove -C option from configure script

### ISSUE THREAD

**Issue by youpong** [TanmayPatil105/procfetch#130]
Shouldn't we remove the `-C` option from the `configure` script  because we no longer plan to use it?

The -C option was intended to be used by the package manager Homebrew, but as a result, the --prefix option is used instead.

**Comment by youpong** [comment]
If there are no objections I will create a pull request to remove -C option.

**Comment by TanmayPatil105** [comment]
Yupp go ahead!
Currently busy with other stuff :/
